apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fraudshield-api
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.fraudshield.example.com
      secretName: fraudshield-tls
  rules:
    - host: api.fraudshield.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fraudshield-api
                port:
                  number: 80
